name: Quick Check

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  qc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build & run compose
        run: |
          docker compose build app
          docker compose up -d --force-recreate
          docker compose ps

      - name: Quick check (make ci)
        run: |
          make ci
