# .github/workflows/quick-check.yml
name: Quick Check

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  qc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare .env (from example)
        run: |
          set -euo pipefail
          if [ -f .env.example ]; then
            cp .env.example .env
          fi
          # Valori minime ca să nu pice docker compose
          grep -q '^APP_PORT=' .env || echo 'APP_PORT=8001' >> .env
          grep -q '^POSTGRES_PASSWORD=' .env || echo 'POSTGRES_PASSWORD=postgres' >> .env

      - name: Quick check (make ci)
        run: make ci
